Document: spirv-reflect
Title: Debian spirv-reflect Manual
Author: <insert document author here>
Abstract: This manual describes what spirv-reflect is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spirv-reflect/spirv-reflect.sgml.gz

Format: postscript
Files: /usr/share/doc/spirv-reflect/spirv-reflect.ps.gz

Format: text
Files: /usr/share/doc/spirv-reflect/spirv-reflect.text.gz

Format: HTML
Index: /usr/share/doc/spirv-reflect/html/index.html
Files: /usr/share/doc/spirv-reflect/html/*.html
